spring:
  datasource:
    #url: jdbc:oracle:thin:@bdt.clweios6cmmg.us-east-2.rds.amazonaws.com:1521/bdt
    #username: admin
    #password: admin123
    url: jdbc:oracle:thin:@localhost:1521/xe
    username: user_bdt
    password: admin
    driver-class-name: oracle.jdbc.driver.OracleDriver
  jpa:
    hibernate:
      #ddl-auto: create-drop
      ddl-auto: none
    #generate-ddl: true
    show-sql: true
